version: '2.2'
services:
  postgre:
    image: postgres:16.0
    restart: always
    command: postgres -c 'max_connections=200'
    mem_limit: 512m
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=dbpassword
    ports:
      - '5432:5432'
